# Base image
FROM node as base

# Make folder to put our files in
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/frontend

# Set working directory so that all subsequent command runs in this folder
WORKDIR /usr/src/app/frontend

# Copy package json and install dependencies
COPY package.json .
RUN npm install

# Copy the app
COPY . .

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL ${REACT_APP_API_URL}

# Set env variables
ENV PORT=3000
# ENV PATH /usr/src/app/frontend/node_modules/.bin:$PATH

# install serve
RUN npm install -g serve

# Expose port to access server
EXPOSE ${PORT}

# Command to run the app
CMD ["npm", "start"]
# CMD [ "serve", "-s", "build"]