# Base image
FROM node as base

# Make folder to put our files in
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/frontend

# Set working directory so that all subsequent command runs in this folder
WORKDIR /usr/src/app/frontend

# Copy package json and install dependencies
COPY package.json .
RUN npm install

# Copy the app
COPY . .

# Expose port to access server
EXPOSE 3000

# Command to run the app
CMD [ "npm", "start" ]